title:            Special character proposal
tagline:          Unity, community and celebration.
description:      A proposal to change the special character at Te Ra Waldorf School
#baseurl:  /specialcharacter
#Comment out url when working locally to resolve base urls correctly
url: http://utunga.github.io/specialcharacter

# Links to include in top navigation
# For external links add external: true
links:
  - title: Proposal
    url: /proposal
  - title: About this site
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Pacific/Auckland
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
